### ISSUE TITLE
Emulate a keypress event when filling fields

### ISSUE THREAD

**Issue by jhass** [keeweb/keeweb-connect#13]
Using Firefox 88 on macOS 11.3 I have at least one site where filling credentials does not trigger the validation mechanism and it thinks the field is still empty when hitting submit. Adding and removing a space space before submitting seems to trigger the validations and then works as expected. I can only suspect this is because the extension does not fire some event handler when filling the field.

Unfortunately the only example I have at hand so far is onelogin.com, so likely something you won't be able to test on yourself.

**Comment by antelle** [comment]
Hi! How do you log in on onelogin.com? I tried entering company name here: https://app.onelogin.com/login, but it works.

**Comment by antelle** [comment]
Just came across a similar thing on T-Mobile, maybe if I fix it, it will also work in your case.

**Comment by jhass** [comment]
Yeah I wasn't sure if you can test it without signing up to their service first. I fooled around a bit and found https://test.onelogin.com works to reproduce the issue :)

**Comment by antelle** [comment]
It was a forgotten `bubble`, now your website works.

**Comment by antelle** [comment]
Published v0.3.6, you can either try it from releases, or wait until Google updates it in the store (about 2-3 days)

**Comment by jhass** [comment]
Thanks so much!
