### ISSUE TITLE
Auto logined when captcha exists

### ISSUE THREAD

**Issue by himekifee** [keeweb/keeweb-connect#16]
As the title described, the autofill will trigger the auto-login even when a captcha or other field is required. This is not the desired behaviour. I'm not sure if there is an option for that. A solution would be adding an option for auto-enter. Thanks for your work.

**Comment by antelle** [comment]
Hi! There’s an option to insert credentials in the context menu.

**Comment by himekifee** [comment]
Any plan for an option to change the default behaviour of clicking the extension logo?

**Comment by antelle** [comment]
Nope. We trigger form submit by default and that's it. If the website handles this properly, the form should not be submitted and it should display a validation error in place. Older websites can submit the form and present an error on return, I assume that's what's going on.
"Smart" (a.k.a. always bugged) logic won't be implemented in KeeWeb Connect.

**Comment by antelle** [comment]
hint: you can also assign a separate shortcut to insert login/username.
