### ISSUE TITLE
Non-autosubmit keyboard shortcuts do not work

### ISSUE THREAD

**Issue by synchrone** [keeweb/keeweb-connect#17]
KeeWeb: 1.18.6
KeeWeb Connect: 0.3.6
Firefox: 88.0.1 (64-bit)
Ubuntu: 18.04.5

* https://github.com/keeweb/keeweb-connect/blob/master/src/background/commands.ts#L27 calls `runCommand` with no `url` property
* `runCommand` at https://github.com/keeweb/keeweb-connect/blob/master/src/background/commands.ts#L42 immediately returns with no action because url is missing (even though it's available from tab object)

**Comment by antelle** [comment]
Hi! Thanks for reporting, will fix it soon

**Comment by synchrone** [comment]
Fixing in https://github.com/keeweb/keeweb-connect/pull/26

**Comment by antelle** [comment]
Will be released soon in v0.3.7
