### ISSUE TITLE
Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings

### ISSUE THREAD

**Issue by synchrone** [keeweb/keeweb-connect#2]
I'm trying out the release 0.1.3, using Firefox 88, with KeeWeb 1.17.6 on Ubuntu 18.04.5

```
$ /home/syn/build/keeweb-firefox/keeweb-native-messaging-host
Expected origin
```

Installed the native manifest manually as per https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests :
```
$ cat ~/.mozilla/native-messaging-hosts/net.antelle.keeweb.keeweb_connect.json 
{
  "name": "net.antelle.keeweb.keeweb_connect",
  "description": "Example host for native messaging",
  "path": "/home/syn/build/keeweb-firefox/keeweb-native-messaging-host",
  "type": "stdio",
  "allowed_extensions": [ "keeweb-connect@keeweb.info" ]
}
```

After clicking "connect" in settings: 
![Screenshot from 2021-04-30 10-19-34](https://user-images.githubusercontent.com/528545/116661750-39361900-a995-11eb-9f98-734f73e9e128.png)

Is there a pre-release KeeWeb build that's necessary to test the extension? I couldn't find any keeweb-side setting or a plugin.

**Comment by antelle** [comment]
Hi! Yes, you need to download KeeWeb from here: https://github.com/keeweb/keeweb-ci-sandbox/releases/tag/v1.17.6

**Comment by synchrone** [comment]
A minor issue is that package has native host binary non-executable by default. Also it was not yet updated for backwards compatibility with ubuntu 18.04+.

Other than that - it works!

**Comment by antelle** [comment]
Thanks! Fixed the permissions and kicked a new build, it will appear in ≈30min there.

**Comment by antelle** [comment]
Done: https://github.com/keeweb/keeweb-ci-sandbox/releases/tag/untagged-380a1c86b3833ffc4bea
Not sure why the release is made untagged, some CI weirdness, I'll look into it.

Works for me as-in on Ubuntu 20.04, I haven't installed 18.04 yet, but I assume it should be okay.

By the way, for Firefox, the extension is already in Store, if you click the Download link in KeeWeb settings, you can download it from there.

However, for now, it's not as fresh as the extension that you can download here, so for testing it's recommended to install latest releases manually. I pushed the extension to stores just to get links for KeeWeb, I'll make proper CI for the extension soon.
