### ISSUE TITLE
Untranslated short description of the extension

### ISSUE THREAD

**Issue by Matthaiks** [keeweb/keeweb-connect#20]
Missing string for "Password autofill for KeeWeb"

KeeWeb Connect 0.3.6

Firefox 89:
![A](https://user-images.githubusercontent.com/3577122/120236151-e8e3fc80-c25b-11eb-9153-fe76810c7b2c.png)

Edge 91.0.864.37:
![B](https://user-images.githubusercontent.com/3577122/120236148-e8e3fc80-c25b-11eb-9eed-201867e535b8.png)

**Comment by antelle** [comment]
Done! Added it to OneSky
