### ISSUE TITLE
Firefox extension can't connect Linux

### ISSUE THREAD

**Issue by iscraigh** [keeweb/keeweb-connect#22]
Using an Ubuntu variant
Keepass 1.18.6
firefox 89.0.1 (snap package)
Error: Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.
extension debug: Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    updatePopupStats moz-extension://203b8a45-d949-4de6-a658-ad8c0b4a4f2d/lib/ui-service.js:173
I have keeweb open and the database unlocked
firefox browser enabled 

I looked in the net.antelle.keeweb.keeweb_connect file and confirmed the path to the native messaging host, also confirmed permissions.
 "path": "/usr/share/keeweb-desktop/keeweb-native-messaging-host"

ls -l /usr/share/keeweb-desktop/keeweb-native-messaging-host
-rwxr-xr-x 1 root root 328032 May 19 01:45 /usr/share/keeweb-desktop/keeweb-native-messaging-host

Any mor info I can give just ask.

**Comment by antelle** [comment]
Hi! Let's see, what happens if you inspect the so-called background page of the extension? A link to it can be found in browser extension settings.

**Comment by iscraigh** [comment]
Okay so I was messing around and removed the Firefox snap package and installed using apt and everything works as expected

**Comment by antelle** [comment]
Great!
