### ISSUE TITLE
Suggestion: top level menu option "Connect with KeeWeb"

### ISSUE THREAD

**Issue by Stephan-P** [keeweb/keeweb-connect#23]
When no KeeWeb database tab is opened, one has to manually open it in order to make use of KeeWeb Connect's autofill features.
Opening KeeWeb could be done manually from a bookmark, or via the KeeWeb Connect menu: Options - Connect with KeeWeb.
Wouldn't it be nice to have this item in the top of the KeeWeb Connect menu: Connect with KeeWeb?
One mouse click less and very handy as KeeWeb Connect provides you the one stop shopping experience.
Little effort - Great experience

**Comment by Stephan-P** [comment]
Additional idea:
There's no action associated to clicking the KeeWeb Connect icon.
How about this: Click the KeeWeb Connect icon with the left mouse button and a/the KeeWeb database tab is opened.

**Comment by antelle** [comment]
Hi! "Connect with KeeWeb" is always optional and it exists in extension settings only for debugging purposes, that you can test the connection. When you trigger any of extension functions (for example, password auto-fill), it will check the connection and connect if necessary. So, there's no need in a button, or any other way of UI for connection.

I was thinking, maybe it's for some reason broken for you and KeeWeb doesn't pop up when you select any of items?

> There's no action associated to clicking the KeeWeb Connect icon.

It should auto-fills username + password.
