### ISSUE TITLE
Unable to connect to brave browser 

### ISSUE THREAD

**Issue by Abdulee** [keeweb/keeweb-connect#24]
Hi, here's the error i encounter when trying to connect with Brave on Ubuntu 20.04LTS based distro. Browser integration is checked for both chrome(since i thought brave is chromium based) and other browsers.. Another thing to add is that with firefox on the same system it integrates perfectly.
Another thing to add I have brave-browser installed as native package(not as a flatpak or snap)
```
Connection state: Error

Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.
```

**Comment by antelle** [comment]
Hi! You need to create a native messaging manifest manually for custom browsers: https://github.com/keeweb/keeweb/wiki/Browser%20AutoFill#other-browsers
