### ISSUE TITLE
Pull in German translations

### ISSUE THREAD

**Issue by max-wittig** [keeweb/keeweb-connect#25]
I'm not sure what the process it for the tool to pull in a new language and commit the changes.

A while ago, I've translated everything to German here: https://keeweb.oneskyapp.com/collaboration/translate/project/project/382232/language/550

Any additional steps that I need to take?

Thanks :)

**Comment by antelle** [comment]
Thank you for the reminder! Somehow I missed a notification from OneSky. Pulled the translations, will make a release with it soon.

**Comment by max-wittig** [comment]
Awesome thanks 👍
