### ISSUE TITLE
Auto-type keystrokes setting ignored 

### ISSUE THREAD

**Issue by elbowz** [keeweb/keeweb-connect#29]
I hope this is not duplicate or there is information about that somewhere...

Keeweb Connect extension don't follow the keystrokes setting (eg. {USERNAME}{TAB}...) stored in the entry, when "submit the form automatically"...instead old auto-type system (ctrl+alt+t) works like expected.

Thanks!

**Comment by antelle** [comment]
Hi! KeeWeb-Connect will not follow auto-type settings, extension just types as it is. Entering fields using the extension is an alternative to auto-typing.
