### ISSUE TITLE
KeeWeb host disconnected Specified native messaging host not found

### ISSUE THREAD

**Issue by blitzdose** [keeweb/keeweb-connect#3]
I always get this error in the console on Microsoft Edge (The chromium version).

I installed this version of KeeWeb: https://github.com/keeweb/keeweb-ci-sandbox

I tried to add the extension to the "allowed_origins" and even tried to change the path of the "native messaging host" but nothing helped.

When i try to run the "keeweb-native-messaging-host.exe" in PowerShell i get "Expected origin" as the output.

Did i miss something or this this a bug?

**Comment by antelle** [comment]
Hi! What does it say if you inspect the background page of the extension?

**Comment by blitzdose** [comment]
```
Connecting to KeeWeb

KW {action: "change-public-keys", extensionName: "KeeWeb Connect", version: "0.1", ... }

KeeWeb host disconnected Specified native messaging host not found.

KeeWeb disconnected

Connect error Error: Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.
    at Backend.rejectPendingRequests (background.js:715)
    at TransportNativeMessaging.<anonymous> (background.js:655)
    at TransportNativeMessaging.emit (background.js:160)
    at TransportNativeMessaging.portDisconnected (background.js:1467)
    at background.js:1443
```

Thats the full output in the console

**Comment by antelle** [comment]
So, this is the installation issue, have you created the native messaging manifest yourself or you did it using KeeWeb?
Could you please check if there's a record in Windows Registry for the host? This key:

```
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\com.my_company.my_app
```

https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=windows#step-3---copy-the-native-messaging-host-manifest-file-to-your-system

**Comment by blitzdose** [comment]
The Installation itself created it. I already checked that. The content of the manifest looked right too.

**Comment by antelle** [comment]
Hm, that's strange. If you open the manifest, does the extension ID there match what you see in Edge when you open extension options?

**Comment by antelle** [comment]
Another thing to check: does the executable (keeweb-native-host-messaging.exe) written in the JSON exist?
Maybe Edge needs to be restarted after installation to read the registry again?

**Comment by blitzdose** [comment]
I have done a bit of research and found the problem:
While looking at the Edge log i noticed, that the problem is: "Invalid native messaging host name specified" So i looked again at the manifest and the name parameter was set to: "org.keepassxc.keepassxc_browser" (Maybe a copy paste issue?) I changed that to your name "net.antelle.keeweb.keeweb_connect" and it works without a problem. But I also had to add the extension ID to the manifest file. There where only two IDs that where different to mine.

Thanks for your help. KeeWeb is awesome!

**Comment by antelle** [comment]
Do I understand it right that:
- you opened Settings in KeeWeb and enabled KeeWeb Connect for Edge
- it created the a registry entry and a file called `net.antelle.keeweb.keeweb_connect.json`
- this file contains `org.keepassxc.keepassxc_browser` inside

?

**Comment by blitzdose** [comment]
I remeber that I tried to enable KeePassXC-Browser as a troubleshooting-step. I tried it again and this changed the name. But the error was the same before i enabled KeePassXC-Browser the first time in the KeeWeb settings. 
And the file that got created is named `native-messaging.chrome.json` and not `net.antelle.keeweb.keeweb_connect.json`

**Comment by blitzdose** [comment]
I tried a fresh install to see what my first problem was and I think i finally know what happend:

- I installed everything and it didn't work.
- I tried different troubleshooting steps e.g. enable KeePassXC-Browser
- This changed the name in the .json file to `org.keepassxc.keepassxc_browser`
- It changed nothing noticeable so i disabled KeePassXC-Browser again but the file didn't change.
- Then i added my extension ID to the file (I think this was the important step but the name was already changed so it didn't solve the problem)


With a fresh install i managed to get it to work with these steps:

- Install the KeeWeb-ci-sandbox Version
- Install the Extension
- Download the keeweb-native-messaging-host from this GitHub site
- Change the already existing native-messaging-host in the Installation Folder of KeeWeb `C:\Program Files\KeeWeb` (I don't know if this step is really necessary)
- Add the extension ID to the `native-messaging.chrome.json` file specified in the registry entry 
- Restart Edge AND KeeWeb and everything works fine

**Comment by antelle** [comment]
Interesting, enabling KeePassXC-Browser should change its own file, I'll check why it happens, thanks!

**Comment by antelle** [comment]
Fixed it, now it will be written to different files:
- `native-messaging-kwc.chrome.json`
- `native-messaging-kpxc.chrome.json`
