### ISSUE TITLE
Unable to install on Safari

### ISSUE THREAD

**Issue by bnzo** [keeweb/keeweb-connect#32]
Extension not showing in Safari Extension Tab.
Tried to install it from the AppSore and from the repo, tried to reboot with no luck.
Extension is working great in Firefox and the following config:

- Apple M1
- macOS 12.0.1 (21A559)
- Safari 15.1 (17612.2.9.1.20)
- Keeweb 1.18.7
- Keeweb Connect 0.3.7
<img width="592" alt="Screenshot 2021-11-19 at 14 56 44" src="https://user-images.githubusercontent.com/17174973/142634214-8ff67ec3-698c-48da-bed1-a0cdc16acebe.png">
<img width="904" alt="Screenshot 2021-11-19 at 14 56 25" src="https://user-images.githubusercontent.com/17174973/142634216-74314dea-bedd-4738-8f5f-440093756232.png">

**Comment by antelle** [comment]
Hm, it works for me. Not sure how to debug it, actually, it's kind of standard stuff for extensions.

**Comment by bnzo** [comment]
Thanks @antelle, glad it is an isolate case. I made some researches leading me to a solution. By simply running a terminal command, the extension works now properly!
Not sure why it happens as others Safari extensions were installed without any issues.

The command might be helpful if it happens to future users: 

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user`
